global:
  scrape_interval: 30s

  external_labels:
    monitor: nxthdr

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['[2a06:de00:50:cafe:10::106]:9093']

rule_files:
  - /config/alerts.yml

scrape_configs:
  - job_name: prometheus
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: caddy
    scheme: http
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::a]:2019']

  - job_name: redpanda-public
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::103]:9644']
    metrics_path: /public_metrics
  
  - job_name: redpanda
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::103]:9644']
    metrics_path: /metrics

  - job_name: chproxy
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::102]:9090']
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        replacement: chproxy_$1
