global:
  scrape_interval: 30s

  external_labels:
    monitor: nxthdr

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['[2a06:de00:50:cafe:10::106]:9093']

rule_files:
  - /config/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: proxy
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::a]:2019']

  - job_name: as215011.net
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::10]:2019']

  - job_name: geofeed
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::11]:2019']

  - job_name: nxthdr.dev
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::100]:2019']

  - job_name: clickhouse
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::101]:9126']

  - job_name: chproxy
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::102]:9090']
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        replacement: chproxy_$1

  - job_name: redpanda
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::103]:9644']
    metrics_path: /metrics

  - job_name: redpanda-public
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::103]:9644']
    metrics_path: /public_metrics

  - job_name: node-exporter
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::107]:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::108]:8080']

  - job_name: loki
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::109]:3100']

  - job_name: risotto
    static_configs:
      - targets: ['[2a06:de00:50:cafe:10::1000]:3000']