---
core:
  hosts:
    coreams01:
      ansible_host: ams01.core.infra.nxthdr.dev
  vars:
    ansible_user: nxthdr

ixp:
  hosts:
    ixpams01:
      ansible_host: ams01.ixp.infra.nxthdr.dev
      tailscale_ip: 100.64.0.3
    ixpams02:
      ansible_host: ams02.ixp.infra.nxthdr.dev
      tailscale_ip: 100.64.0.4
    ixpfra01:
      ansible_host: fra01.ixp.infra.nxthdr.dev
      tailscale_ip: 100.64.0.2
    ixpcdg01:
      ansible_host: cdg01.ixp.infra.nxthdr.dev
      tailscale_ip: 100.64.0.9
    ixpcdg02:
      ansible_host: cdg02.ixp.infra.nxthdr.dev
      tailscale_ip: 100.64.0.6
  vars:
    ansible_user: nxthdr

vlt:
  hosts:
    vltewr01:
      ansible_host: ewr01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8a3::/48
    vltcdg01:
      ansible_host: cdg01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8a4::/48
    vltsgp01:
      ansible_host: sgp01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8a5::/48
    vltsyd01:
      ansible_host: syd01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8a2::/48
    vltsao01:
      ansible_host: sao01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8a6::/48
    vltjnb01:
      ansible_host: jnb01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8a7::/48
    vltlax01:
      ansible_host: lax01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8a8::/48
    vltnrt01:
      ansible_host: nrt01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8a9::/48
    vltbom01:
      ansible_host: bom01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8aa::/48
    vltmex01:
      ansible_host: mex01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8ab::/48
    vltsto01:
      ansible_host: sto01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8ac::/48
    vltscl01:
      ansible_host: scl01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8ad::/48
    vltsea01:
      ansible_host: sea01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8ae::/48
    vltmel01:
      ansible_host: mel01.vlt.infra.nxthdr.dev
      uniprobe0: 2a0e:97c0:8af::/48
  vars:
    ansible_user: nxthdr
