apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: https://loki.nxthdr.dev
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Prometheus
  type: prometheus
  orgId: 1
  url: https://prometheus.nxthdr.dev
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
