# Generated by render/render_terraform.py from inventory.yml
# Do not edit directly.


# core servers
provider "docker" {
  host     = "ssh://nxthdr@ams01.core.infra.nxthdr.dev:22"
  alias    = "coreams01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

# ixp servers
provider "docker" {
  host     = "ssh://nxthdr@ams01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpams01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@ams02.ixp.infra.nxthdr.dev:22"
  alias    = "ixpams02"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@fra01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpfra01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpcdg01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg02.ixp.infra.nxthdr.dev:22"
  alias    = "ixpcdg02"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

# vlt servers
provider "docker" {
  host     = "ssh://nxthdr@ewr01.vlt.infra.nxthdr.dev:22"
  alias    = "vltewr01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg01.vlt.infra.nxthdr.dev:22"
  alias    = "vltcdg01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@sgp01.vlt.infra.nxthdr.dev:22"
  alias    = "vltsgp01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@syd01.vlt.infra.nxthdr.dev:22"
  alias    = "vltsyd01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@sao01.vlt.infra.nxthdr.dev:22"
  alias    = "vltsao01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@jnb01.vlt.infra.nxthdr.dev:22"
  alias    = "vltjnb01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@lax01.vlt.infra.nxthdr.dev:22"
  alias    = "vltlax01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@nrt01.vlt.infra.nxthdr.dev:22"
  alias    = "vltnrt01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@bom01.vlt.infra.nxthdr.dev:22"
  alias    = "vltbom01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@mex01.vlt.infra.nxthdr.dev:22"
  alias    = "vltmex01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@sto01.vlt.infra.nxthdr.dev:22"
  alias    = "vltsto01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@scl01.vlt.infra.nxthdr.dev:22"
  alias    = "vltscl01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@sea01.vlt.infra.nxthdr.dev:22"
  alias    = "vltsea01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@mel01.vlt.infra.nxthdr.dev:22"
  alias    = "vltmel01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}
