# Generated by render/render_terraform.py from inventory.yml
# Do not edit directly.


# core servers
provider "docker" {
  host     = "ssh://nxthdr@ams01.core.infra.nxthdr.dev:22"
  alias    = "coreams01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

# ixp servers
provider "docker" {
  host     = "ssh://nxthdr@ams01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpams01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@ams02.ixp.infra.nxthdr.dev:22"
  alias    = "ixpams02"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@fra01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpfra01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpcdg01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg02.ixp.infra.nxthdr.dev:22"
  alias    = "ixpcdg02"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

# vlt servers
provider "docker" {
  host     = "ssh://nxthdr@ewr01.vlt.infra.nxthdr.dev:22"
  alias    = "vltewr01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg01.vlt.infra.nxthdr.dev:22"
  alias    = "vltcdg01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@sgp01.vlt.infra.nxthdr.dev:22"
  alias    = "vltsgp01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}
