# Generated by render/render_terraform.py from inventory.yml
# Do not edit directly.


module "ixp_ixpams01" {
  source = "./modules/ixp"
  providers = {
    docker = docker.ixpams01
  }
  hostname          = "ixpams01"
  headscale_authkey = var.headscale_authkey
}

module "ixp_ixpams02" {
  source = "./modules/ixp"
  providers = {
    docker = docker.ixpams02
  }
  hostname          = "ixpams02"
  headscale_authkey = var.headscale_authkey
}

module "ixp_ixpfra01" {
  source = "./modules/ixp"
  providers = {
    docker = docker.ixpfra01
  }
  hostname          = "ixpfra01"
  headscale_authkey = var.headscale_authkey
}

module "ixp_ixpcdg01" {
  source = "./modules/ixp"
  providers = {
    docker = docker.ixpcdg01
  }
  hostname          = "ixpcdg01"
  headscale_authkey = var.headscale_authkey
}

module "ixp_ixpcdg02" {
  source = "./modules/ixp"
  providers = {
    docker = docker.ixpcdg02
  }
  hostname          = "ixpcdg02"
  headscale_authkey = var.headscale_authkey
}
