# WARNING
# This file is generated by render/ scripts and should not be edited directly.
#

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "3.6.2"
    }
    vultr = {
      source  = "vultr/vultr"
      version = "~> 2.21"
    }
    porkbun = {
      source  = "cullenmcdermott/porkbun"
      version = "~> 0.2"
    }
  }
}

# Vultr Provider
provider "vultr" {
  api_key = var.vultr_api_key
}

# Porkbun Provider
provider "porkbun" {
  api_key    = var.porkbun_api_key
  secret_key = var.porkbun_secret_api_key
}

# Dynamically Generated Docker Providers
## core Servers
provider "docker" {
  host     = "ssh://nxthdr@ams01.core.infra.nxthdr.dev:22"
  alias    = "coreams01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

## ixp Servers
provider "docker" {
  host     = "ssh://nxthdr@ams01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpams01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@ams02.ixp.infra.nxthdr.dev:22"
  alias    = "ixpams02"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@fra01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpfra01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg01.ixp.infra.nxthdr.dev:22"
  alias    = "ixpcdg01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg02.ixp.infra.nxthdr.dev:22"
  alias    = "ixpcdg02"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

## vlt Servers
provider "docker" {
  host     = "ssh://nxthdr@atl01.vlt.infra.nxthdr.dev:22"
  alias    = "vltatl01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

provider "docker" {
  host     = "ssh://nxthdr@cdg01.vlt.infra.nxthdr.dev:22"
  alias    = "vltcdg01"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

