# WARNING
# This file is generated by render/ scripts and should not be edited directly.
#
# VLT Infrastructure Management
# This file provisions Vultr servers and DNS records based on inventory.yml

# Data source to read SSH keys from Vultr account
data "vultr_ssh_key" "nxthdr_keys" {
  for_each = toset(var.vultr_ssh_key_names)

  filter {
    name   = "name"
    values = [each.value]
  }
}

# Local variables for VLT server configuration
locals {
  # Map of VLT servers from inventory
  vlt_servers = {
    "vltatl01" = {
      region       = "atl"  # Extract region from hostname (e.g., vltatl01 -> atl)
      uniprobe0    = "2a0e:97c0:8a3::/48"
      ansible_host = "atl01.vlt.infra.nxthdr.dev"
    }
    "vltcdg01" = {
      region       = "cdg"  # Extract region from hostname (e.g., vltatl01 -> atl)
      uniprobe0    = "2a0e:97c0:8a4::/48"
      ansible_host = "cdg01.vlt.infra.nxthdr.dev"
    }
    "vltfra01" = {
      region       = "fra"  # Extract region from hostname (e.g., vltatl01 -> atl)
      uniprobe0    = "2a0e:97c0:8a5::/48"
      ansible_host = "fra01.vlt.infra.nxthdr.dev"
    }
  }

  # Extract SSH key IDs
  ssh_key_ids = [for key in data.vultr_ssh_key.nxthdr_keys : key.id]
}

# Create VLT servers using the module
module "vlt_server" {
  source   = "./modules/vlt-server"
  for_each = local.vlt_servers

  hostname     = each.key
  region       = each.value.region
  ssh_key_ids  = local.ssh_key_ids

  # Optional: Override defaults if needed
  # plan         = "vc2-1c-1gb"  # Default
  # os_id        = 2625  # Debian 13 x64 trixie (default)
}

# Outputs for all VLT servers
output "vlt_servers" {
  description = "Information about all VLT servers"
  value = {
    for hostname, server in module.vlt_server : hostname => {
      id          = server.id
      fqdn        = server.fqdn
      main_ip     = server.main_ip
      v6_main_ip  = server.v6_main_ip
      v6_network  = server.v6_network
      region      = server.region
      status      = server.status
    }
  }
}