# Generated by render/render_terraform.py from inventory.yml
# Do not edit directly.


locals {
  vlt_servers = {
    "vltatl01" = {
      region       = "atl"
      uniprobe0    = "2a0e:97c0:8a3::/48"
      ansible_host = "atl01.vlt.infra.nxthdr.dev"
    }
    "vltcdg01" = {
      region       = "cdg"
      uniprobe0    = "2a0e:97c0:8a4::/48"
      ansible_host = "cdg01.vlt.infra.nxthdr.dev"
    }
  }
}

module "vlt_vltatl01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltatl01
  }
  hostname = "vltatl01"
}

module "vlt_vltcdg01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltcdg01
  }
  hostname = "vltcdg01"
}
