# Generated by render/render_terraform.py from inventory.yml
# Do not edit directly.


locals {
  vlt_servers = {
    "vltewr01" = {
      region       = "ewr"
      uniprobe0    = "2a0e:97c0:8a3::/48"
      ansible_host = "ewr01.vlt.infra.nxthdr.dev"
    }
    "vltcdg01" = {
      region       = "cdg"
      uniprobe0    = "2a0e:97c0:8a4::/48"
      ansible_host = "cdg01.vlt.infra.nxthdr.dev"
    }
    "vltsgp01" = {
      region       = "sgp"
      uniprobe0    = "2a0e:97c0:8a5::/48"
      ansible_host = "sgp01.vlt.infra.nxthdr.dev"
    }
    "vltsyd01" = {
      region       = "syd"
      uniprobe0    = "2a0e:97c0:8a2::/48"
      ansible_host = "syd01.vlt.infra.nxthdr.dev"
    }
    "vltsao01" = {
      region       = "sao"
      uniprobe0    = "2a0e:97c0:8a6::/48"
      ansible_host = "sao01.vlt.infra.nxthdr.dev"
    }
    "vltjnb01" = {
      region       = "jnb"
      uniprobe0    = "2a0e:97c0:8a7::/48"
      ansible_host = "jnb01.vlt.infra.nxthdr.dev"
    }
    "vltlax01" = {
      region       = "lax"
      uniprobe0    = "2a0e:97c0:8a8::/48"
      ansible_host = "lax01.vlt.infra.nxthdr.dev"
    }
    "vltnrt01" = {
      region       = "nrt"
      uniprobe0    = "2a0e:97c0:8a9::/48"
      ansible_host = "nrt01.vlt.infra.nxthdr.dev"
    }
    "vltbom01" = {
      region       = "bom"
      uniprobe0    = "2a0e:97c0:8aa::/48"
      ansible_host = "bom01.vlt.infra.nxthdr.dev"
    }
    "vltmex01" = {
      region       = "mex"
      uniprobe0    = "2a0e:97c0:8ab::/48"
      ansible_host = "mex01.vlt.infra.nxthdr.dev"
    }
    "vltsto01" = {
      region       = "sto"
      uniprobe0    = "2a0e:97c0:8ac::/48"
      ansible_host = "sto01.vlt.infra.nxthdr.dev"
    }
    "vltscl01" = {
      region       = "scl"
      uniprobe0    = "2a0e:97c0:8ad::/48"
      ansible_host = "scl01.vlt.infra.nxthdr.dev"
    }
    "vltsea01" = {
      region       = "sea"
      uniprobe0    = "2a0e:97c0:8ae::/48"
      ansible_host = "sea01.vlt.infra.nxthdr.dev"
    }
    "vltmel01" = {
      region       = "mel"
      uniprobe0    = "2a0e:97c0:8af::/48"
      ansible_host = "mel01.vlt.infra.nxthdr.dev"
    }
  }
}

module "vlt_vltewr01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltewr01
  }
  hostname = "vltewr01"
}

module "vlt_vltcdg01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltcdg01
  }
  hostname = "vltcdg01"
}

module "vlt_vltsgp01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltsgp01
  }
  hostname = "vltsgp01"
}

module "vlt_vltsyd01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltsyd01
  }
  hostname = "vltsyd01"
}

module "vlt_vltsao01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltsao01
  }
  hostname = "vltsao01"
}

module "vlt_vltjnb01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltjnb01
  }
  hostname = "vltjnb01"
}

module "vlt_vltlax01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltlax01
  }
  hostname = "vltlax01"
}

module "vlt_vltnrt01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltnrt01
  }
  hostname = "vltnrt01"
}

module "vlt_vltbom01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltbom01
  }
  hostname = "vltbom01"
}

module "vlt_vltmex01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltmex01
  }
  hostname = "vltmex01"
}

module "vlt_vltsto01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltsto01
  }
  hostname = "vltsto01"
}

module "vlt_vltscl01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltscl01
  }
  hostname = "vltscl01"
}

module "vlt_vltsea01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltsea01
  }
  hostname = "vltsea01"
}

module "vlt_vltmel01" {
  source = "./modules/vlt-containers"
  providers = {
    docker = docker.vltmel01
  }
  hostname = "vltmel01"
}
