{
 "title": "Risotto",
 "tags": [ "service" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router",
    "query": {
     "query": "label_values(risotto_bgp_peers,router)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "risotto_bgp_peers{router='$router'}",
     "legendFormat": "{{router}}"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "risotto_bgp_updates{router='$router'}",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Updates per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "risotto_updates_per_minute{router_addr='$router'}",
     "legendFormat": "{{router_addr}}"
    }
   ]
  }
 ]
}