api:
  address: 2a06:de00:50:cafe:10::1000
  port: 3000

bmp:
  address: '::'
  port: 4000

kafka:
  brokers: "[2a06:de00:50:cafe:10::103]:9092"
  auth_protocol: PLAINTEXT
  topic: risotto-updates

state:
  enable: true
  path: /data/dump.json
  save_interval: 10
