databases:
  clickhouse:
    dsn: "clickhouse+native://chproxy@[2a06:de00:50:cafe:10::101]:9000"

metrics:
  risotto_updates_per_minute:
    type: gauge
    description: Risotto updates per minute
    labels: [ router_addr ]

  saimiris_results_per_minute:
    type: gauge
    description: Saimiris results per minute
    labels: [ agent_id ]

queries:
  risotto_updates_per_minute:
    databases: [ clickhouse ]
    metrics: [ risotto_updates_per_minute ]
    interval: 1m
    sql: |
      WITH toStartOfMinute(now() - INTERVAL 1 MINUTE) AS timeStart, toStartOfMinute(now()) as timeEnd
      SELECT router_addr, Count() AS risotto_updates_per_minute
      FROM risotto.updates
      WHERE timestamp >= timeStart
      AND timestamp < timeEnd
      GROUP BY router_addr

  saimiris_results_per_minute:
    databases: [ clickhouse ]
    metrics: [ saimiris_results_per_minute ]
    interval: 1m
    sql: |
      WITH toStartOfMinute(now() - INTERVAL 1 MINUTE) AS timeStart, toStartOfMinute(now()) as timeEnd
      SELECT agent_id, Count() AS saimiris_results_per_minute
      FROM saimiris.results
      WHERE timestamp >= timeStart
      AND timestamp < timeEnd
      GROUP BY agent_id
