import sys
from pathlib import Path

import jinja2
import yaml
from ansible_vault import Vault

BASE_DIR = Path(__file__).resolve().parent.parent
INVENTORY_FILE = BASE_DIR / "inventory" / "inventory.yml"
SECRETS_FILE = BASE_DIR / "secrets" / "secrets.yml"
TEMPLATE_DIR = BASE_DIR / "templates" / "terraform"
OUTPUT_DIR = BASE_DIR / "terraform"

GENERATED_HEADER = (
    "# Generated by render/render_terraform.py from inventory.yml\n"
    "# Do not edit directly.\n\n"
)


def generate_docker_providers(inventory):
    """Generate docker provider blocks for all hosts."""
    lines = [GENERATED_HEADER]
    for group_name, group_data in inventory.items():
        hosts = group_data.get("hosts", {})
        if not hosts:
            continue
        group_vars = group_data.get("vars", {})
        lines.append(f"# {group_name} servers")
        for host_name, host_data in hosts.items():
            host_data = host_data or {}
            ansible_host = host_data.get("ansible_host", host_name)
            ansible_user = host_data.get(
                "ansible_user", group_vars.get("ansible_user", "nxthdr")
            )
            lines.append('provider "docker" {')
            lines.append(f'  host     = "ssh://{ansible_user}@{ansible_host}:22"')
            lines.append(f'  alias    = "{host_name}"')
            lines.append(
                '  ssh_opts = ["-o", "StrictHostKeyChecking=no", '
                '"-o", "UserKnownHostsFile=/dev/null"]'
            )
            lines.append("}\n")
    return "\n".join(lines)


def generate_ixp(inventory):
    """Generate ixp.tf with module calls for each IXP host."""
    ixp_data = inventory.get("ixp", {})
    hosts = ixp_data.get("hosts", {})
    if not hosts:
        return GENERATED_HEADER

    lines = [GENERATED_HEADER]
    for host_name in hosts:
        lines.append(f'module "ixp_{host_name}" {{')
        lines.append('  source = "./modules/ixp"')
        lines.append("  providers = {")
        lines.append(f"    docker = docker.{host_name}")
        lines.append("  }")
        lines.append(f'  hostname          = "{host_name}"')
        lines.append("  headscale_authkey = var.headscale_authkey")
        lines.append("}\n")
    return "\n".join(lines)


def generate_vlt(inventory):
    """Generate vlt.tf with vlt_servers locals and module calls for each VLT host."""
    vlt_data = inventory.get("vlt", {})
    hosts = vlt_data.get("hosts", {})
    if not hosts:
        return GENERATED_HEADER

    lines = [GENERATED_HEADER]

    # Generate locals.vlt_servers map (used by vlt-infrastructure.tf)
    lines.append("locals {")
    lines.append("  vlt_servers = {")
    for host_name, host_data in hosts.items():
        host_data = host_data or {}
        region = host_name[3:6]
        uniprobe0 = host_data.get("uniprobe0", "")
        ansible_host = host_data.get("ansible_host", "")
        lines.append(f'    "{host_name}" = {{')
        lines.append(f'      region       = "{region}"')
        lines.append(f'      uniprobe0    = "{uniprobe0}"')
        lines.append(f'      ansible_host = "{ansible_host}"')
        lines.append("    }")
    lines.append("  }")
    lines.append("}\n")

    # Generate module calls for VLT containers
    for host_name in hosts:
        lines.append(f'module "vlt_{host_name}" {{')
        lines.append('  source = "./modules/vlt-containers"')
        lines.append("  providers = {")
        lines.append(f"    docker = docker.{host_name}")
        lines.append("  }")
        lines.append(f'  hostname = "{host_name}"')
        lines.append("}\n")
    return "\n".join(lines)


def main():
    vault_password = sys.stdin.readline().strip()
    if not vault_password:
        print("Error: No vault password provided.", file=sys.stderr)
        sys.exit(1)

    # Load inventory
    try:
        with open(INVENTORY_FILE, "r") as f:
            inventory = yaml.safe_load(f)
        if not inventory:
            print(
                f"Error: Inventory file {INVENTORY_FILE} is empty.",
                file=sys.stderr,
            )
            sys.exit(1)
    except FileNotFoundError:
        print(
            f"Error: Inventory file not found at {INVENTORY_FILE}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Load secrets
    if not SECRETS_FILE.exists():
        print(f"Error: Secrets file not found at {SECRETS_FILE}", file=sys.stderr)
        sys.exit(1)

    try:
        vault = Vault(vault_password)
        with open(SECRETS_FILE, "rb") as f:
            secrets = vault.load(f.read())
        if not isinstance(secrets, dict):
            secrets = {}
    except Exception as e:
        print(f"Error decrypting secrets: {e}", file=sys.stderr)
        sys.exit(1)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Render terraform.tfvars from Jinja2 template (secrets)
    tfvars_template = TEMPLATE_DIR / "terraform.tfvars.j2"
    if tfvars_template.is_file():
        jinja_env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(TEMPLATE_DIR)),
            trim_blocks=True,
            lstrip_blocks=True,
            undefined=jinja2.StrictUndefined,
        )
        template = jinja_env.get_template(tfvars_template.name)
        rendered = template.render(secrets)
        with open(OUTPUT_DIR / "terraform.tfvars", "w") as f:
            f.write(rendered)
        print("Rendered: terraform.tfvars")

    # Generate wiring files from inventory
    generated_files = {
        "docker-providers.tf": generate_docker_providers(inventory),
        "ixp.tf": generate_ixp(inventory),
        "vlt.tf": generate_vlt(inventory),
    }

    for filename, content in generated_files.items():
        with open(OUTPUT_DIR / filename, "w") as f:
            f.write(content)
        print(f"Generated: {filename}")


if __name__ == "__main__":
    main()
