api:
  address: 2a06:de00:50:cafe:10::1000
  port: 3000

bmp:
  address: '::'
  port: 4000

kafka:
  address: 2a06:de00:50:cafe:10::103
  port: 9092
  topic: bgp-updates
  batch_max_size: 1000
  batch_wait: 5
