{
 "title": "BMP",
 "tags": [ "core" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "router",
    "label": "Router",
    "query": {
     "query": "label_values(risotto_peer_established,router)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(risotto_peer_established{router='$router'})",
     "legendFormat": "Connected Peers"
    }
   ]
  },
  {
   "title": "Updates in Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "risotto_state_updates{router='$router'}",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Received BMP Messages ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(risotto_bmp_messages_total{router=\"$router\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Received Updates Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(risotto_rx_updates_total{router=\"$router\"}[$__rate_interval])",
     "legendFormat": "{{ peer }}"
    }
   ]
  },
  {
   "title": "Transmitted Updates Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(risotto_tx_updates_total{router=\"$router\"}[$__rate_interval])",
     "legendFormat": "{{ peer }}"
    }
   ]
  },
  {
   "title": "Updates per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(time_received_ns) AS time, Count() AS \"${router}\"\nFROM bmp.updates\nWHERE $__timeFilter(time) AND router_addr == toIPv6('${router}')\nGROUP BY time\nORDER BY time"
    }
   ]
  }
 ]
}