{
 "title": "Saimiris",
 "tags": [ "service" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "agent",
    "label": "Agent",
    "query": "SELECT DISTINCT agent_id FROM saimiris.results ORDER BY agent_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Packets Sending Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(saimiris_sender_sent_total{agent='$agent'}[10m])",
     "legendFormat": "{{ agent }}"
    }
   ]
  },
  {
   "title": "Packets Receiving Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(saimiris_receiver_received_total{agent='$agent'}[10m])",
     "legendFormat": "{{ agent }}"
    }
   ]
  },
  {
   "title": "Results per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(time_received_ns) AS time, Count() AS \"${agent}\"\nFROM saimiris.results\nWHERE $__timeFilter(time) AND agent_id == '${agent}'\nGROUP BY time\nORDER BY time"
    }
   ]
  }
 ]
}