{
 "title": "Traffic",
 "tags": [ "core" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT IPv6NumToString(sampler_address) FROM flows.records"
   }
  ]
 },
 "panels": [
  {
   "title": "Instant traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfSecond(time_flow_start_ns) AS \"time\",\n    sum(bytes * max2(sampling_rate, 1)) AS bytes\nFROM flows.records\nWHERE $__timeFilter(time) AND IPv6NumToString(sampler_address) == '$host'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH flows_agg AS (\n    SELECT\n        toStartOfSecond(time_flow_start_ns) AS \"time\",\n        src_addr,\n        sum(bytes * max2(sampling_rate, 1)) AS bytes\n    FROM flows.records\n    WHERE $__timeFilter(time) AND IPv6NumToString(sampler_address) == '$host'\n    GROUP BY time, src_addr\n)\nSELECT\n    \"time\",\n    IPv6NumToString(src_addr),\n    bytes,\nFROM flows_agg\nWHERE src_addr IN (\n    SELECT src_addr\n    FROM flows_agg\n    GROUP BY src_addr\n    ORDER BY sum(bytes) DESC\n    LIMIT 10\n)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Top source ports",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH flows_agg AS (\n    SELECT\n        toStartOfSecond(time_flow_start_ns) AS \"time\",\n        tuple(proto, src_port) AS port,\n        sum(bytes * max2(sampling_rate, 1)) AS bytes\n    FROM flows.records\n    WHERE $__timeFilter(time) AND IPv6NumToString(sampler_address) == '$host'\n    GROUP BY time, port\n)\nSELECT\n    \"time\",\n    port.1 || '/' || toString(port.2) as src_port_string,\n    bytes\nFROM flows_agg\nWHERE port IN (\n    SELECT port\n    FROM flows_agg\n    GROUP BY port\n    ORDER BY sum(bytes) DESC\n    LIMIT 10\n)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH flows_agg AS (\n    SELECT\n        toStartOfSecond(time_flow_start_ns) AS \"time\",\n        dst_addr,\n        sum(bytes * max2(sampling_rate, 1)) AS bytes\n    FROM flows.records\n    WHERE $__timeFilter(time) AND IPv6NumToString(sampler_address) == '$host'\n    GROUP BY time, dst_addr\n)\nSELECT\n    \"time\",\n    IPv6NumToString(dst_addr),\n    bytes,\nFROM flows_agg\nWHERE dst_addr IN (\n    SELECT dst_addr\n    FROM flows_agg\n    GROUP BY dst_addr\n    ORDER BY sum(bytes) DESC\n    LIMIT 10\n)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Top destination ports",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH flows_agg AS (\n    SELECT\n        toStartOfSecond(time_flow_start_ns) AS \"time\",\n        tuple(proto, dst_port) AS port,\n        sum(bytes * max2(sampling_rate, 1)) AS bytes\n    FROM flows.records\n    WHERE $__timeFilter(time) AND IPv6NumToString(sampler_address) == '$host'\n    GROUP BY time, port\n)\nSELECT\n    \"time\",\n    port.1 || '/' || toString(port.2) as dst_port_string,\n    bytes\nFROM flows_agg\nWHERE port IN (\n    SELECT port\n    FROM flows_agg\n    GROUP BY port\n    ORDER BY sum(bytes) DESC\n    LIMIT 10\n)\nORDER BY time"
    }
   ]
  }
 ]
}