groups:
- name: core-service-down
  rules:
  - alert: Core_Service_Proxy_Down
    expr: up{job="proxy"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'core service {{ $labels.job }} is down in {{ $labels.instance }}'

  - alert: Core_Service_Redpanda_Down
    expr: up{job="redpanda"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'core service {{ $labels.job }} is down'

  - alert: Core_Service_Clickhouse_Down
    expr: up{job="clickhouse"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'core service {{ $labels.job }} is down'

  - alert: Core_Service_Chproxy_Down
    expr: up{job="chproxy"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'core service {{ $labels.job }} is down'

  - alert: Core_Service_Loki_Down
    expr: up{job="loki"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'core service {{ $labels.job }} is down'

  - alert: Core_Service_Grafana_Down
    expr: up{job="grafana"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'core service {{ $labels.job }} is down'

  - alert: Core_Service_Risotto_Down
    expr: up{job="risotto"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'core service {{ $labels.job }} is down'

  - alert: Core_Service_Goflow_Down
    expr: up{job="goflow"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'core service {{ $labels.job }} is down'

- name: host
  rules:
  - alert: Host_Disk_Full
    expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100 < 10
    for: 1m
    labels:
      severity: warning
    annotations:
      title: host disk is almost full in {{ $labels.instance }}

  - alert: Host_Out_Of_Memory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: host almost out of memory in {{ $labels.instance }}

- name: monitoring-down
  rules:
  - alert: Monitoring_Service_Alloy_Down
    expr: up{job="alloy"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      title: 'monitoring service {{ $labels.job }} is down in {{ $labels.instance }}'

  - alert: Monitoring_Service_Node_Exporter_Down
    expr: up{job="node-exporter"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      title: 'monitoring service {{ $labels.job }} is down in {{ $labels.instance }}'

  - alert: Monitoring_Service_Cadvisor_Down
    expr: up{job="cadvisor"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      title: 'monitoring service {{ $labels.job }} is down in {{ $labels.instance }}'

- name: risotto
  rules:
  - alert: Risotto_No_BGP_Peers
    expr: absent(risotto_peer_established)
    for: 1m
    labels:
      severity: critical
    annotations:
      title: 'risotto reports no BGP peers'

- name: saimiris
  rules:
  - alert: Probing_Service_Saimiris_Down
    expr: up{job="saimiris"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      title: 'probing service {{ $labels.job }} is down in {{ $labels.instance }}'
