# ansible-playbook -i inventory/ -e "base_dir=$(pwd)" --ask-become-pass playbooks/install-saimiris.yml
---
- hosts: vlt
  become: yes
  tasks:
  - name: Install Rust
    ansible.builtin.shell: |
      curl "https://sh.rustup.rs" -sSf | sh -s -- -y

  - name: Install required libraries for compilation
    become: yes
    ansible.builtin.apt:
      pkg:
      - libpcap-dev
      - libsasl2-dev
      - libssl-dev

  - name: Remove existing Saimiris installation
    ansible.builtin.shell: |
      rm -rf /home/nxthdr/.cargo/bin/saimiris

  - name: Create `cargo-install-saimiris` directory
    ansible.builtin.file:
      path: /home/nxthdr/cargo-install-saimiris
      state: directory

  - name: Install Saimiris
    ansible.builtin.shell: |
      CARGO_TARGET_DIR=/home/nxthdr/cargo-install-saimiris /home/nxthdr/.cargo/bin/cargo install saimiris --git https://github.com/nxthdr/saimiris.git

  - name: Remove build artifacts
    ansible.builtin.file:
      path: /home/nxthdr/cargo-install-saimiris
      state: absent

  - name: Copy systemd file
    ansible.builtin.copy:
      src: "{{ base_dir }}/templates/shared/saimiris/saimiris.service"
      dest: /lib/systemd/system/saimiris.service

  - name: Reload systemd
    ansible.builtin.command: systemctl daemon-reload

  - name: Enable and restart saimiris
    ansible.builtin.systemd_service:
      enabled: true
      state: restarted
      name: saimiris
