# ansible-playbook -i inventory/ -e "base_dir=$(pwd)" --ask-become-pass playbooks/install-rsyslog.yml
---
- hosts: core, ixp, vlt
  become: yes
  tasks:
  - name: Install rsyslog
    apt:
      name: rsyslog
      state: present

  - name: Copy rsyslog configuration
    ansible.builtin.copy:
      src: "{{ base_dir }}/templates/config/shared/rsyslog/rsyslog.conf"
      dest: /etc/rsyslog.conf

  - name: Restart rsyslog
    ansible.builtin.systemd:
      name: rsyslog
      enabled: true
      state: restarted
