---
- hosts: vlt
  tasks:
  - name: Install Rust
    ansible.builtin.shell: |
      curl "https://sh.rustup.rs" -sSf | sh -s -- -y

  - name: Install required libraries for compilation
    become: yes
    ansible.builtin.apt:
      pkg:
      - libpcap-dev
      - libsasl2-dev
      - libssl-dev

  - name: Create `cargo-install-saimiris` directory
    ansible.builtin.file:
      path: /home/nxthdr/cargo-install-saimiris
      state: directory

  - name: Install Saimiris
    ansible.builtin.shell: |
      CARGO_TARGET_DIR=/home/nxthdr/cargo-install-saimiris /home/nxthdr/.cargo/bin/cargo install saimiris --git https://github.com/nxthdr/saimiris.git

  - name: Remove build artifacts
    ansible.builtin.file:
      path: /home/nxthdr/cargo-install-saimiris
      state: absent