# ansible-playbook -i inventory/ --ask-become-pass playbooks/install-vlt-firewall.yml
---
- hosts: vlt
  become: yes
  tasks:
  - name: Rule to allow alloy to reach saimiris prometheus endpoint
    community.general.ufw:
      rule: allow
      port: 8080
      src: 172.18.0.0/16
      proto: tcp
